<?php
     $session = new Zend_Session_Namespace('fullname');
     $loggedin = new Zend_Session_Namespace('loggedin');

?>
<header id="header" xmlns="http://www.w3.org/1999/html"><p><h5>Welcome <?=$session->fullname?:"User";?></h5>
    <?php
    if ($loggedin->status == 1) {
        ?>
        <h5 style="top-align:10px"><a href="/customer/authentication/logout" style="margin-left: 90%;">Logout</a></h5>
        <?php
    }
    ?>
</p>
</header>