<?php
 $loggedin = new Zend_Session_Namespace('loggedin');
 if ($loggedin->status==1) {

?>
<nav id="left" class="column" style="    right: 191px;">

	<h3>Customer</h3>
	<ul>
		<li><a href="/truck/vehicle/list">Vehicle</a></li>
		<li><a href="/truck/purchase/list">Purchase</a></li>
		<li><a href="/truck/order/list">Order</a></li>
        <li><a href="/truck/purchase/listpo">Create PO</a></li>
	</ul>
</nav>
 <?php
 }
 ?>